[build]
builder = "mcr.microsoft.com/dotnet/sdk:8.0"
app_dir = "/app"
build_cmd = "dotnet publish -c Release -o /app/publish"

[run]
cmd = "dotnet /app/publish/YourApp.dll"
env = { ASPNETCORE_URLS = "http://0.0.0.0:5000" }

[dependencies]
# Add any other dependencies that are required for your app here
# For example, you might need to include additional system packages for your app to run correctly.

[platform]
name = "dotnet"

[logs]
# Optional logging configuration
